### ISSUE TITLE
Multiple for loops in builder causes crash

### ISSUE THREAD

**Issue by TheAngryByrd** [edgarfgp/Fabulous.AST#31]
👋 Found some fun bugs

Having multiple (at least 3) for loops within a builder can cause issues.  I've found two different variations:

1. Having some items then 3 for loops:

```fsharp
    [<Test>]
    let ``stress test`` () =
        let result =
            Namespace("DummyNamespace").isRecursive() {
                Abbrev($"Foo", Type.FromString "string")
                Abbrev($"bar", Type.FromString "string")
                for i = 0 to 10 do
                    Abbrev($"T{i}", Type.FromString "string")
                for i = 10 to 20 do
                    Abbrev($"T{i}", Type.FromString "string")
                for i = 20  to 30 do
                    Abbrev($"T{i}", Type.FromString "string")
            }
            |> Tree.compile
            |> CodeFormatter.FormatOakAsync
            |> Async.RunSynchronously
        Assert.NotNull result
```

```
  Failed stress test [6 ms]
  Error Message:
   System.ArgumentException : Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
  Stack Trace:
     at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at Fabulous.AST.StackAllocatedCollections.MutStackArray1.combineMut[v](T`1& a, T`1 b) in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST\Core\Array.fs:line 483
   at Fabulous.AST.Tests.WidgetTests.stress test() in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST.Tests\WidgetTests.fs:line 34
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

2. Having 3 for loops:

```fsharp

    [<Test>]
    let ``stress test2`` () =
        let result =
            Namespace("DummyNamespace").isRecursive() {
                for i = 0 to 10 do
                    Abbrev($"T{i}", Type.FromString "string")
                for i = 10 to 20 do
                    Abbrev($"T{i}", Type.FromString "string")
                for i = 20  to 30 do
                    Abbrev($"T{i}", Type.FromString "string")
            }
            |> Tree.compile
            |> CodeFormatter.FormatOakAsync
            |> Async.RunSynchronously
        Assert.NotNull result
```

```
  Error Message:
   System.InvalidOperationException : The input sequence has an insufficient number of elements.
  Stack Trace:
     at Microsoft.FSharp.Collections.ArrayModule.Take[T](Int32 count, T[] array) in D:\a\_work\1\s\src\fsharp\FSharp.Core\array.fs:line 147
   at Fabulous.AST.Helpers.getWidgetsFromWidgetCollection(Widget widget, WidgetCollectionAttributeDefinition def) in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST\Core\Helpers.fs:line 60
   at Fabulous.AST.Helpers.getNodesFromWidgetCollection[T](Widget widget, WidgetCollectionAttributeDefinition def) in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST\Core\Helpers.fs:line 70
   at Fabulous.AST.Namespace.WidgetKey@40-7.Invoke(Widget widget) in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST\Widgets\Namespaces\Namespace.fs:line 41
   at Fabulous.AST.Widgets.definition@10-1.Invoke(Widget x)
   at Fabulous.AST.Tree.compile[node](WidgetBuilder`1 root) in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST\Tree.fs:line 9
   at Fabulous.AST.Tests.WidgetTests.stress test2() in C:\Users\jimmy\Repositories\public\TheAngryByrd\Fabulous.AST\src\Fabulous.AST.Tests\WidgetTests.fs:line 53
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

**Comment by edgarfgp** [comment]
@TheAngryByrd  This should be fixed in https://www.nuget.org/packages/Fabulous.AST/0.6.1
Thanks for the report :)
